packages:
  - apps/*

allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  core-js: true
  esbuild: true
  prisma: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - prisma
